### PR TITLE
Add skeleton of OAuth 2.0 Password Grant implementation

### PR DESCRIPTION
**Pull request by knardi**

### CODE REVIEW

**Comment by pickles27** [comment]
Looks good to meeeeee

:approved:

**Comment by knardi** [comment]
```
2022-10-10T03:35:48.034069+00:00 app[web.1]: file:///app/dist/auth/app.js:8
2022-10-10T03:35:48.034070+00:00 app[web.1]: const keys = process.env.SECURE_KEY.split(",").map((hexKey) => Buffer.from(hexKey, "hex"));
2022-10-10T03:35:48.034071+00:00 app[web.1]: ^
2022-10-10T03:35:48.034071+00:00 app[web.1]: 
2022-10-10T03:35:48.034072+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'split')
2022-10-10T03:35:48.034072+00:00 app[web.1]: at file:///app/dist/auth/app.js:8:37
2022-10-10T03:35:48.034074+00:00 app[web.1]: at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
2022-10-10T03:35:48.034074+00:00 app[web.1]: at async Promise.all (index 0)
2022-10-10T03:35:48.034074+00:00 app[web.1]: at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
2022-10-10T03:35:48.034074+00:00 app[web.1]: at async loadESM (node:internal/process/esm_loader:88:5)
2022-10-10T03:35:48.034075+00:00 app[web.1]: at async handleMainPromise (node:internal/modules/run_main:61:12)
```

Womp. Need to add that to the environment in Heroku.

**Comment by pickles27** [comment]
Loll 😅

**Comment by knardi** [comment]
```
curl -X POST -d 'grant_type=password&username=foo&password=bar' https://codegolfxyz-pr-20.herokuapp.com/oauth/token
{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwicm9sZSI6InJvbGUiLCJleHAiOjE2Njc5NjUzODcsImlhdCI6MTY2NTM3MzM4N30.17Vx-PxVcwlpGGhjvlo9rvxSrSB66tMEXgCjrZ9mxAI","token_type":"Bearer","expires_in":2592000,"scope":"user"}
```

It wooooorrrkkkssss 🚀

**Pull request merged**
